foreground = yes
pid = /tmp/stunnel.pid

[postgres-client]
client = yes
accept = 0.0.0.0:15432
connect = postgresql-aws.svc.plus:5443
verify = 2
CAfile = /etc/ssl/certs/ca-certificates.crt
checkHost = postgresql-aws.svc.plus
