---
docker_project_dir: /opt/cloud-neutral/docker-compose
docker_project_name: compose-runtime
docker_compose_file: docker-compose.yml
docker_registry_server: ""
docker_registry_username: ""
docker_registry_password: ""
docker_pull_images: true
docker_preferred_command: docker
docker_login_when_configured: true
docker_start_when_requested: true
docker_ps_when_requested: false
