foreground = yes
debug = 5

[postgres-client]
client = yes
accept = 0.0.0.0:15432
connect = host.docker.internal:5433
verify = 2
CAfile = /etc/ssl/certs/ca-certificates.crt
checkHost = host.docker.internal
socket = l:TCP_NODELAY=1
socket = r:TCP_NODELAY=1
socket = l:SO_KEEPALIVE=1
socket = r:SO_KEEPALIVE=1
TIMEOUTclose = 0
TIMEOUTidle = 43200
