console_frontend_deploy_dir: "{{ lookup('env', 'DEPLOY_DIR') | default('/opt/console-svc-plus', true) }}"
console_frontend_project_name: "console-svc-plus"
console_frontend_runtime_env_file_local: "{{ lookup('env', 'RUNNER_TEMP') | default('/tmp', true) }}/console-svc-plus.env.runtime"

console_frontend_image: "{{ lookup('env', 'FRONTEND_IMAGE') }}"
console_frontend_primary_domain: "{{ lookup('env', 'PRIMARY_DOMAIN') }}"
console_frontend_secondary_domain: "{{ lookup('env', 'SECONDARY_DOMAIN') }}"

console_frontend_ghcr_registry: "{{ lookup('env', 'GHCR_REGISTRY') | default('ghcr.io', true) }}"
console_frontend_ghcr_username: "{{ lookup('env', 'GHCR_USERNAME') }}"
console_frontend_ghcr_password: "{{ lookup('env', 'GHCR_PASSWORD') }}"
