---
agent_proxy_domain: jp-xhttp-contabo.svc.plus
agent_proxy_target_ip: 46.250.251.132
agent_proxy_script_url: https://raw.githubusercontent.com/cloud-neutral-toolkit/agent.svc.plus/main/scripts/setup-proxy.sh
agent_proxy_script_path: /tmp/setup-proxy.sh
agent_proxy_auth_url: https://accounts.svc.plus
agent_proxy_internal_service_token: ""
agent_proxy_open_stunnel_5443: false
agent_proxy_upgrade_only: false
agent_proxy_standalone: false
