- name: Render stage
  ansible.builtin.import_tasks: render.yml

- name: Diff stage
  ansible.builtin.import_tasks: diff.yml

- name: Preflight stage
  ansible.builtin.import_tasks: preflight.yml

- name: Apply stage
  ansible.builtin.import_tasks: apply.yml

- name: Verify stage
  ansible.builtin.import_tasks: verify.yml
