
docker_compose_lite_apply: true

docker_compose_lite_accounts_image: asia-northeast1-docker.pkg.dev/xzerolab-480008/cloud-run-source-deploy/accounts.svc.plus/accounts-svc-plus:d00593cdbe210afcd2e9256f9b01eacc1dd5a82f
docker_compose_lite_preview_accounts_image: asia-northeast1-docker.pkg.dev/xzerolab-480008/cloud-run-source-deploy/accounts.svc.plus/preview-accounts-svc-plus:ea3d6aec06d0c604fd08c815366b99189b7604dc
docker_compose_lite_rag_image: asia-northeast1-docker.pkg.dev/xzerolab-480008/cloud-run-source-deploy/rag-server.svc.plus/rag-server-svc-plus:646e539f8f7388f3d08980a6ace505ea1fd9b5db

docker_compose_lite_accounts_env:
  CONFIG_TEMPLATE: /app/config/account.cloudrun.yaml
  DB_USER: postgres
  DB_NAME: account
  DB_PASSWORD: "otdcRLTJamszk3AE"
  SMTP_HOST: smtp.qq.com
  SMTP_PORT: "587"
  SMTP_FROM: XControl Account <manbuzhe2009@qq.com>
  SMTP_USERNAME: manbuzhe2009@qq.com
  SMTP_PASSWORD: "hfbmubplfxnpcabg"

docker_compose_lite_rag_env:
  DB_USER: postgres
  DB_NAME: knowledge_db
  DB_PASSWORD: "otdcRLTJamszk3AE"
  NVIDIA_API_KEY: "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"
