---
openclaw_source_host: openclaw.svc.plus
openclaw_domain: openclaw.svc.plus
openclaw_service_port: 18789
openclaw_workspace: /opt/data
openclaw_data_backend: local # local|gcs
openclaw_runtime_mode: systemd # systemd|docker
openclaw_manage_caddy: true
openclaw_manage_dns: false
openclaw_manage_migration: false
openclaw_manage_runtime_state: true
openclaw_migrate_data_dir: false
openclaw_bucket_name: openclawbot-data
openclaw_user_name: root
openclaw_node_package: "openclaw@2026.3.24"
openclaw_docker_image: ""
openclaw_docker_compose_dir: /opt/openclaw
openclaw_caddyfile_path: /etc/caddy/Caddyfile
openclaw_user_systemd_dir: /root/.config/systemd/user
openclaw_root_config_dir: /root/.config/openclawbot
openclaw_runtime_dir: /root/.openclaw
openclaw_cloudflare_zone_name: ""
openclaw_cloudflare_zone_id: ""
openclaw_cloudflare_api_token: ""
openclaw_cloudflare_record_type: A
openclaw_cloudflare_record_content: ""
openclaw_cloudflare_proxied: false
